name: python codes test
on:
  push:
    branches:
      - master
      - xmeng
  pull_request:
    branches:
      - master 
      - xmeng

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.7]
        
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 Nextflow/nf-core-ninjaindex/docker_files/ninjaindex/ --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 docker_files/ninjaMap/*.py --count --select=E9,F63,F7,F82 --show-source --statistics
    - name: Test with pytest
     run: |
       #python -m pytest test.py
